#include "hal_data.h"
#include "string.h"
#include "bsp/bsp.h"
// #include "dac/dac.h"
#include "can/can.h"

extern unsigned char sound1[155616];

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{

    CAN_init();

    while(true);

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

