#include "hal_data.h"
#include "string.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
void R_LED_Control(uint8_t number);
void CAN_Frame_Setting(uint32_t id, uint8_t dlc, uint8_t *data);
FSP_CPP_FOOTER

#define STANDARD_CAN_FRAME          8

char                                opcode[] = "CONTROL";
can_frame_t                         g_can_tx_frame;
can_frame_t                         g_can_rx_frame;

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    uint32_t id = 1U;
    uint8_t data_field[] = "Example1";

    R_CAN_Open(&g_can0_ctrl, &g_can0_cfg);
    CAN_Frame_Setting(id, STANDARD_CAN_FRAME, data_field);
    R_CAN_Write(&g_can0_ctrl, 0, &g_can_tx_frame);

    while(true);

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}
void R_LED_Control(uint8_t number)
{
    switch(number)
    {
        case 0:
            R_PORT10->PCNTR1 = 0x07000700;
            R_PORT11->PCNTR1 = 0x00010001;
            break;
        case 1:
            R_PORT10->PCNTR1 = 0x06000700;
            R_PORT11->PCNTR1 = 0x00010001;
            break;
        case 2:
            R_PORT10->PCNTR1 = 0x05000700;
            R_PORT11->PCNTR1 = 0x00010001;
            break;
        case 3:
            R_PORT10->PCNTR1 = 0x03000700;
            R_PORT11->PCNTR1 = 0x00010001;
            break;
        case 4:
            R_PORT10->PCNTR1 = 0x07000700;
            R_PORT11->PCNTR1 = 0x00000001;
            break;
    }
}
void CAN_Frame_Setting(uint32_t id, uint8_t dlc, uint8_t *data)
{
    g_can_tx_frame.id = id;
    g_can_tx_frame.id_mode = CAN_ID_MODE_STANDARD;
    g_can_tx_frame.type = CAN_FRAME_TYPE_DATA;

    g_can_tx_frame.data_length_code = dlc;

    if (strlen((const char *)data) <= 8)
        memcpy(g_can_tx_frame.data, data, dlc);
    else
        memset(g_can_tx_frame.data, 0, sizeof(uint8_t) * STANDARD_CAN_FRAME);
}
void can_callback(can_callback_args_t *p_args)
{
    switch(p_args->event)
    {
        case CAN_EVENT_RX_COMPLETE:
            g_can_rx_frame = p_args->frame;
            memset(&(p_args->frame), 0, sizeof(can_frame_t));

            if(!strncmp((char *)&(g_can_rx_frame.data[0]), opcode, strlen(opcode)))
                R_LED_Control(g_can_rx_frame.data[7] - 48);
            break;
        default:
            break;
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
